### ISSUE TITLE
cannot parse [\-]

### ISSUE THREAD

**Issue by robmcl4** [jviereck/regjsparser#109]
version: 0.6.7

I expected the regexp `[\-]` to parse as a characterClass with one identifier value, `-`. Instead, I saw:

```
SyntaxError: classAtom at position 4
    [\-]
        ^
    at bail (/home/robert/Source/test/node_modules/regjsparser/parser.js:1179:13)
    at parseNonemptyClassRangesNoDash (/home/robert/Source/test/node_modules/regjsparser/parser.js:1125:9)
    at parseHelperClassRanges (/home/robert/Source/test/node_modules/regjsparser/parser.js:1088:13)
    at parseNonemptyClassRanges (/home/robert/Source/test/node_modules/regjsparser/parser.js:1114:14)
    at parseClassRanges (/home/robert/Source/test/node_modules/regjsparser/parser.js:1033:15)
    at parseCharacterClass (/home/robert/Source/test/node_modules/regjsparser/parser.js:1015:15)
    at parseAtomAndExtendedAtom (/home/robert/Source/test/node_modules/regjsparser/parser.js:670:22)
    at parseTerm (/home/robert/Source/test/node_modules/regjsparser/parser.js:484:18)
    at parseAlternative (/home/robert/Source/test/node_modules/regjsparser/parser.js:457:21)
    at parseDisjunction (/home/robert/Source/test/node_modules/regjsparser/parser.js:437:16)
```

To repro:

```javascript
const parse = require('regjsparser').parse;
parse('[\\-]')
```

**Comment by jviereck** [comment]
Thanks for reporting this. I take a look.

**Comment by jviereck** [comment]
This issue got fixed on the main branch and a new version of the library (v0.6.8) was published to npm.

**Comment by jviereck** [comment]
If the issue is not fixed or you run in any other problems, feel free to open the issue once again. Thanks for reporting the issue in first place!

**Comment by robmcl4** [comment]
Thanks! ~I uncovered what I believe is an additional bug which I'll put in another issue.~ (actually this was an issue on my side)
